import { useState } from "react";

function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/);
  if (lines.length < 2) return { headers: [], data: [] };
  const headers = lines[0].split(",").map(h => h.trim().toLowerCase());
  const data = lines.slice(1).map(line => {
    const cells = line.split(",").map(c => c.trim());
    const row = {};
    headers.forEach((h, i) => (row[h] = cells[i]));
    return row;
  });
  return { headers, data };
}

export default function ManagerBrief() {
  const [rows, setRows] = useState([]);
  const [error, setError] = useState("");

  async function onUpload(e) {
    setError("");
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".csv")) {
      setError("Please upload a .csv file (manager_brief.csv).");
      return;
    }
    const text = await file.text();
    const { headers, data } = parseCsv(text);

    // expected columns from export_manager_brief.py
    const required = [
      "scenario",
      "total_cost",
      "avg_coverage",
      "rows_with_shortfall",
      "avg_shortfall_probability",
    ];
    const missing = required.filter(r => !headers.includes(r));
    if (missing.length) {
      setError(`Missing column(s): ${missing.join(", ")}`);
      setRows([]);
      return;
    }

    const cleaned = data.map(r => ({
      scenario: String(r.scenario || "").trim(),
      total_cost: r.total_cost === "" ? null : Number(r.total_cost),
      avg_coverage: r.avg_coverage === "" ? null : Number(r.avg_coverage), // already %
      rows_with_shortfall: r.rows_with_shortfall === "" ? 0 : Number(r.rows_with_shortfall),
      avg_shortfall_probability:
        r.avg_shortfall_probability === "" ? null : Number(r.avg_shortfall_probability), // already %
    }));

    setRows(cleaned);
  }

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-6">
      <h1 className="text-2xl font-bold">Manager Brief</h1>
      <p className="text-sm text-gray-600">
        Upload <code>data/manager_brief.csv</code> generated by the pipeline to see a short, plain-English summary:
        total cost, average coverage, number of rows with shortfall, and the average chance of shortfall.
      </p>

      <div className="p-4 rounded-2xl bg-gray-50 border">
        <label className="block text-sm font-medium mb-2 text-gray-600">Upload manager_brief.csv</label>
        <input
          type="file"
          accept=".csv"
          onChange={onUpload}
          className="file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:bg-gray-800 text-gray-600 file:text-white hover:file:bg-gray-700"
        />
        {error && (
          <p className="mt-3 text-sm text-red-600 bg-red-50 border border-red-200 p-2 rounded">
            {error}
          </p>
        )}
      </div>

      {rows.length > 0 && (
        <div className="overflow-x-auto rounded-2xl border">
          <table className="min-w-full text-sm">
            <thead className="bg-gray-100 text-gray-700">
              <tr>
                <th className="p-3 text-left">Scenario</th>
                <th className="p-3 text-right">Total Cost (period)</th>
                <th className="p-3 text-right">Average Coverage</th>
                <th className="p-3 text-right">Rows with Shortfall</th>
                <th className="p-3 text-right">Avg Chance of Shortfall</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => {
                const risk = r.avg_shortfall_probability;
                const risky = risk != null && risk >= 10; // 10%+
                return (
                  <tr key={r.scenario} className="odd:bg-white even:bg-gray-50">
                    <td className="p-3 capitalize">{r.scenario}</td>
                    <td className="p-3 text-right">
                      {r.total_cost == null ? "—" : `$${r.total_cost.toLocaleString()}`}
                    </td>
                    <td className="p-3 text-right">
                      {r.avg_coverage == null ? "—" : `${r.avg_coverage.toFixed(1)}%`}
                    </td>
                    <td className="p-3 text-right">{r.rows_with_shortfall}</td>
                    <td className="p-3 text-right">
                      {risk == null ? (
                        "—"
                      ) : (
                        <span
                          className={`px-2 py-1 rounded-xl text-xs ${
                            risky
                              ? "bg-red-100 text-red-700 border border-red-200"
                              : "bg-green-100 text-green-700 border border-green-200"
                          }`}
                        >
                          {risk.toFixed(1)}%
                        </span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <div className="text-xs text-gray-500">
        <div className="font-medium mb-1">Notes</div>
        <ul className="list-disc ml-5 space-y-1">
          <li>
            <span className="font-medium">Average Coverage</span> is shown as a percentage (closer to 100% is better).
          </li>
          <li>
            <span className="font-medium">Avg Chance of Shortfall</span> comes from Monte Carlo draws (if available).
            It’s averaged across all (date, shift) rows in a scenario.
          </li>
          <li>
            Red badge marks scenarios with <span className="font-medium">≥ 10%</span> risk of shortfall.
          </li>
        </ul>
      </div>
    </div>
  );
}
