import { useState } from "react";

export default function StaffingResults() {
  const [rows, setRows] = useState([]);
  const [error, setError] = useState("");

  function parseCsv(text) {

    const lines = text.trim().split(/\r?\n/);
    if (lines.length < 2) return { headers: [], data: [] };

    const headers = lines[0].split(",").map(h => h.trim().toLowerCase());
    const data = lines.slice(1).map(line => {
      const cells = line.split(",").map(c => c.trim());
      const obj = {};
      headers.forEach((h, i) => (obj[h] = cells[i]));
      return obj;
    });
    return { headers, data };
  }

  async function onUpload(e) {
    setError("");
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.name.toLowerCase().endsWith(".csv")) {
      setError("Please choose a .csv file.");
      return;
    }

    const text = await file.text();
    const { headers, data } = parseCsv(text);

    const required = [
      "date",
      "shift",
      "scenario",
      "predicted_patients",
      "total_capacity",
      "shortfall",
      "total_cost",
      "coverage_rate",
      "status",
    ];
    const missing = required.filter(r => !headers.includes(r));
    if (missing.length) {
      setError(
        `Missing required column(s): ${missing.join(
          ", "
        )}. Make sure you uploaded staffing_summary.csv from the optimizer.`
      );
      setRows([]);
      return;
    }


    const numeric = ["predicted_patients", "total_capacity", "shortfall", "total_cost", "coverage_rate"];
    const cleaned = data.map(r => {
      const out = { ...r };
      numeric.forEach(k => (out[k] = r[k] === "" ? null : Number(r[k])));
      return out;
    });

    setRows(cleaned);
  }

 
  const kpi = (() => {
    if (rows.length === 0) return null;
    const totalCost = rows.reduce((s, r) => s + (r.total_cost || 0), 0);
    const avgCoverage =
      rows.reduce((s, r) => s + (r.coverage_rate || 0), 0) / rows.length;
    const shortfallSlices = rows.filter(r => (r.shortfall || 0) > 0).length;
    return { totalCost, avgCoverage, shortfallSlices };
  })();

  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6">
      <h1 className="text-2xl font-bold">Staffing Optimization Results</h1>
      <p className="text-sm text-gray-600">
        Upload the <span className="font-medium">staffing_summary.csv</span> file
        generated by <code>analysis/optimize_staffing.py</code>.
        This page shows a readable summary for managers.
      </p>

      <div className="p-4 rounded-2xl bg-gray-50 border">
        <label className="block text-sm font-medium mb-2">
          Upload staffing_summary.csv
        </label>
        <input
          type="file"
          accept=".csv"
          onChange={onUpload}
          className="file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:bg-gray-800 file:text-white hover:file:bg-gray-700"
        />
        <p className="text-xs text-gray-500 mt-2">
          Tip: Run the optimizer first:
          <code className="ml-1">python analysis/optimize_staffing.py</code>
        </p>
        {error && (
          <p className="mt-3 text-sm text-red-600 bg-red-50 border border-red-200 p-2 rounded">
            {error}
          </p>
        )}
      </div>

      {kpi && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-4 rounded-2xl border">
            <div className="text-xs text-gray-500">Total Cost (all rows)</div>
            <div className="text-xl font-semibold">
              ${kpi.totalCost.toLocaleString()}
            </div>
          </div>
          <div className="p-4 rounded-2xl border">
            <div className="text-xs text-gray-500">Average Coverage Rate</div>
            <div className="text-xl font-semibold">
              {(kpi.avgCoverage * 100).toFixed(1)}%
            </div>
            <div className="text-xs text-gray-500">Closer to 100% = better</div>
          </div>
          <div className="p-4 rounded-2xl border">
            <div className="text-xs text-gray-500">Rows with Shortfall</div>
            <div className="text-xl font-semibold">{kpi.shortfallSlices}</div>
            <div className="text-xs text-gray-500">Needs attention</div>
          </div>
        </div>
      )}

      {rows.length > 0 && (
        <div className="overflow-x-auto rounded-2xl border">
          <table className="min-w-full text-sm">
            <thead className="bg-gray-100 text-gray-700">
              <tr>
                <th className="p-3 text-left">Date</th>
                <th className="p-3 text-left">Shift</th>
                <th className="p-3 text-left">Scenario</th>
                <th className="p-3 text-right">Predicted Patients</th>
                <th className="p-3 text-right">Total Capacity (patients)</th>
                <th className="p-3 text-right">Shortfall (patients)</th>
                <th className="p-3 text-right">Total Cost (shift)</th>
                <th className="p-3 text-right">Coverage Rate</th>
                <th className="p-3 text-left">Solver Status</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r, idx) => (
                <tr key={idx} className="odd:bg-white even:bg-gray-50">
                  <td className="p-3">{r.date}</td>
                  <td className="p-3 capitalize">{r.shift}</td>
                  <td className="p-3 capitalize">{r.scenario}</td>
                  <td className="p-3 text-right">
                    {r.predicted_patients?.toLocaleString(undefined, { maximumFractionDigits: 1 })}
                  </td>
                  <td className="p-3 text-right">
                    {r.total_capacity?.toLocaleString(undefined, { maximumFractionDigits: 1 })}
                  </td>
                  <td className="p-3 text-right">
                    {r.shortfall?.toLocaleString(undefined, { maximumFractionDigits: 1 })}
                  </td>
                  <td className="p-3 text-right">
                    {typeof r.total_cost === "number" ? `$${r.total_cost.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : ""}
                  </td>
                  <td className="p-3 text-right">
                    {typeof r.coverage_rate === "number" ? `${(r.coverage_rate * 100).toFixed(1)}%` : ""}
                  </td>
                  <td className="p-3">{r.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <div className="text-xs text-gray-500">
        <div className="font-medium mb-1">Notes</div>
        <ul className="list-disc ml-5 space-y-1">
          <li>
            <span className="font-medium">Predicted Patients</span> comes from
            your forecast file (<code>data/predicted_demand.csv</code>).
          </li>
          <li>
            <span className="font-medium">Total Capacity</span> is based on the
            chosen staffing plan and the capacity per role in{" "}
            <code>config/config.json</code>.
          </li>
          <li>
            <span className="font-medium">Coverage Rate</span> is capped at
            100%. Any <span className="font-medium">Shortfall</span> means more
            staff are needed or the capacity assumptions should be adjusted.
          </li>
        </ul>
      </div>
    </div>
  );
}
